### ISSUE TITLE
Licence Type

### ISSUE THREAD

**Issue by de-ramon** [azmatt/Anaximander#1]
Hi Matt,

thanks for your script!
Which type of licence do you want to use for Anaximander?
GPL v3 would be nice...
I found a bug and want to commit....

regards,

Ralf

**Comment by azmatt** [comment]
Ralf,

Very cool! Haven't even thought about it. Why do you suggest gpl v3?

Matt

**Comment by de-ramon** [comment]
Matt,

if you and the public want to benefit form others, which improve the code, GPL v3 would be fine.

Some examples for forensic software
 * RegRipper uses GPL:
https://github.com/keydet89/RegRipper2.8/blob/master/license.txt
 * netsniff-ng uses GPL:
https://github.com/netsniff-ng/netsniff-ng/blob/master/COPYING
 * Dshell (US Army project), uses the MIT-Licence
https://github.com/USArmyResearchLab/Dshell/blob/master/LICENSE.txt

So, choosing the right licence can help making the world better :)

https://en.wikipedia.org/wiki/GNU_General_Public_License
...
Software under the GPL may be run for all purposes, including commercial purposes and even as a tool for creating proprietary software, for example when using GPL-licensed compilers.[51] Users or companies who distribute GPL-licensed works (e.g. software), may charge a fee for copies or give them free of charge. This distinguishes the GPL from shareware software licenses that allow copying for personal use but prohibit commercial distribution, or proprietary licenses where copying is prohibited by copyright law. The FSF argues that freedom-respecting free software should also not restrict commercial use and distribution (including redistribution):[50] the GPL explicitly states that GPL works may be sold at any price.

In purely private (or internal) use—with no sales and no distribution—the software code may be modified and parts reused without requiring the source code to be released. For sales or distribution, the entire source code need to be made available to end users, including any code changes and additions—in that case, copyleft is applied to ensure that end users retain the freedoms defined above.[52]

However, software running as an application program under a GPL-licensed operating system such as Linux is not required to be licensed under GPL or to be distributed with source-code availability—the licensing depends only on the used libraries and software components and not on the underlying platform.[53] For example, if a program consists only of own original custom software, or is combined with source code from other software components,[54] then the own custom software components need not be licensed under GPL and need not make their code available; even if the underlying operating system used is licensed under the GPL, applications running on it are not considered derivative works.[53] Only if GPLed parts are used in a program (and the program is distributed), then all other source code of the program needs to be made available under the same license terms. The GNU Lesser General Public license (LGPL) was created to have a weaker copyleft than the GPL, in that it does not require own custom-developed source code (distinct from the LGPLed parts) to be made available....

Ralf

**Comment by azmatt** [comment]
Sounds great. Thanks again for the feedback.
